### ISSUE TITLE
Migration Checklist to make laboratory generic

### ISSUE THREAD

**Issue by pirupius** [openmrs/openmrs-esm-laboratory-app#20]
- [x] Update package name and actions CI
- [x] Which Tabs should be maintained
- [ ]  Make review tab configurable
- [ ] Move static concepts to config
- [ ]  implement referral mechanisms
- [x] decouple patient queues from the lab module
